### ISSUE TITLE
The characters indicated in the screenshots below are defective in ALL italics except Thin Italic and Black Italic

### ISSUE THREAD

**Issue by cssobral2013** [uswds/public-sans#104]
If you need, see the screenshots I attached. I used Regular Italic but all the weights mentioned in the title display this problem.

Screenshot 1:
![Sem título](https://user-images.githubusercontent.com/19995437/58840896-d8352780-863d-11e9-9410-e9cb54225262.png)

Screenshot 2:
![Sem título2](https://user-images.githubusercontent.com/19995437/58840897-d8cdbe00-863d-11e9-92f9-8fe9ddde8eab.png)

**Comment by thisisdano** [comment]
Grr. Ok — I can reproduce this and will fix the paths asap.

**Comment by thisisdano** [comment]
New version coming tomorrow!

**Comment by thisisdano** [comment]
This was a problem with the node and path order in the masters.
