### ISSUE TITLE
em-dash not rendering properly in Safari and iOS

### ISSUE THREAD

**Issue by thisisdano** [uswds/public-sans#109]
Example paragraph in Chrome/Firefox:

<img width="628" alt="Screen Shot 2019-07-26 at 9 38 24 AM" src="https://user-images.githubusercontent.com/11464021/61967043-3240d200-af89-11e9-973e-06b20e104f88.png">

The same paragraph in Safari:

<img width="637" alt="Screen Shot 2019-07-26 at 9 38 10 AM" src="https://user-images.githubusercontent.com/11464021/61967052-3bca3a00-af89-11e9-9297-2e8ea24a9c72.png">

This could be related to how it's handling ligatures?

**Comment by thisisdano** [comment]
The em-dashes are also not appearing in iOS browsers

**Comment by thisisdano** [comment]
Currently the font uses a `liga` replacement for `space emdash space` to `space_emdash_space.liga` to help control the amount of space around em-dashes. 

```
sub space emdash space by space_emdash_space.liga;
```
Safari and iOS browsers (webkit?) do not recognize  `liga` statements with a `space` in them — whether this is a bug or intentional, I don't know. 

Additional research indicates that `space`s in font features isn't reliable. However, if I change how this is implemented, and do it with a contextual alternate instead of a ligature, I can make it work in all tested browsers. So, I removed the ligature glyph and its rule, created a `emdash.alt` glyph with reduced sirebearings, and then used the `calt` feature for the replacement:

```
sub space emdash' space by emdash.alt;
```

This works!

**Comment by jimratliff** [comment]
Thanks for the quick action on this, Dan! I wonder if there are other characters that might have this problem, e.g., en dash?

**Comment by thisisdano** [comment]
The em-dash was the only character that used a ligature replacement with a space character so I feel pretty confident that this issue is limited to the em-dash only. I've tested the other ligatures There aren't many of them) and the others are all OK.
