### ISSUE TITLE
The tilde and the macron aren't high in italics as are in romans

### ISSUE THREAD

**Issue by cssobral2013** [uswds/public-sans#111]
If you need, see screenshot attached (tildes):
![Screenshot_20190731-062739-1](https://user-images.githubusercontent.com/19995437/62201009-ead98d80-b35c-11e9-910c-226324a90dbd.png)
Edit: does this happens in other glyphs that use tilde?

**Comment by thisisdano** [comment]
Another great catch — thanks!
