### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by cssobral2013** [uswds/public-sans#112]
Why, for the newest release of Public Sans (1.007, just released now, Aug 06, 2019), did you chose 1374 as the width of colonmonetary.tf in all 18 weights, if the width of all tabular currencies and 0-9 are 1400?

**Comment by cssobral2013** [comment]
Now waiting for a fix.

**Comment by cssobral2013** [comment]
I realized these are unfinished.

**Comment by thisisdano** [comment]
I don't know why the colon didn't get the tabular width I set for the others. Let's re-open this and I'll get it fixed before I release 1.007. Thanks

**Comment by cssobral2013** [comment]
Just for remembering, set all  tabular currencies and 0-9 to 1400. Okay?

**Comment by thisisdano** [comment]
Haha yes — that's the intention! :)
Also changing the tf period and comma to be 600 in all weights/styles.

**Comment by cssobral2013** [comment]
Okay then. Waiting for the release to be launched.
