### ISSUE TITLE
[Italics only] The terminals in lowercase 's' aren't perfectly horizontal

### ISSUE THREAD

**Issue by cssobral2013** [uswds/public-sans#114]
If you need, see the screenshot below (for Italic):
![Sem título](https://user-images.githubusercontent.com/19995437/62666178-a9e30980-b958-11e9-9d68-2a2a5fd6772a.png)

**Comment by cssobral2013** [comment]
Edit: I've fixed this now by myself. See the attachment. Hope you accept!
[Italics.zip](https://github.com/uswds/public-sans/files/3483945/Italics.zip)

**Comment by cssobral2013** [comment]
So, it looks like I'll close this issue.

**Comment by thisisdano** [comment]
I fixed this in #116 and it will go out in the `1.007` release.
