### ISSUE TITLE
The ae ligature is different in italics and in romans

### ISSUE THREAD

**Issue by cssobral2013** [uswds/public-sans#117]
See the screenshot (for Regular & Regular Italic). All weights display this problem.
![IMG_20190813_162211](https://user-images.githubusercontent.com/19995437/62972621-d41a4880-bdea-11e9-9377-4985e267f8da.jpg)

**Comment by cssobral2013** [comment]
As you see, the capital ligature AE doesn't display this problem.

**Comment by thisisdano** [comment]
Are you referring to the terminal angle in the italic here? Or something else?

**Comment by cssobral2013** [comment]
More precisely, the terminal angles should be flat, as are in romans.

Em sex, 1 de nov de 2019 12:09 PM, Dan O. Williams <notifications@github.com>
escreveu:

**Comment by thisisdano** [comment]
Addressed in https://github.com/uswds/public-sans/pull/123
