### ISSUE TITLE
Roman variable font: instance coordinates for Thin and ExtraLight are not multiples of 100

### ISSUE THREAD

**Issue by eliheuer** [uswds/public-sans#119]
On the specimen page instance weights are listed as multiples of 100: https://public-sans.digital.gov/

However, in the glyphs source file ExtraLight is set to 275 and Thin is set to 250.
Please see: Font Info > Instances > Custom Parameters > weightClass

This also causes a [FontBakery](https://github.com/googlefonts/fontbakery) fail, which needs to pass in order to close issue #29:

## Fontbakery report

Fontbakery version: 0.7.14

<details>
<summary><b>[1] PublicSans[wght].ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Check variable font instances have correct coordinate values</summary>

* [com.google.fonts/check/varfont_instance_coordinates](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/varfont_instance_coordinates)
* 🔥 **FAIL** Instance "Thin" wght value is "250.0". It should be "100.0" [code: bad-coordinate]
* 🔥 **FAIL** Instance "ExtraLight" wght value is "275.0". It should be "200.0" [code: bad-coordinate]

</details>
<br>
</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS | 🔎 DEBUG |
|:-----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 1 | 0 | 0 | 0 | 0 | 0 |
| 0% | 100% | 0% | 0% | 0% | 0% | 0% |

Please see the discussion in this pull request for further info: https://github.com/google/fonts/pull/2009#issuecomment-544952435

I'm going to change these values in my fork I'm making the above pull request from, but unless I'm missing something this seems worth change in the upstream source files.

**Comment by thisisdano** [comment]
@eliheuer When I run FontBakery it gives me an error and asks that I change the Thin and ExtraLight values to 250 and 275, respectively.

https://github.com/googlefonts/fontbakery/blob/5bcaa446d6b1ccabe1e8c48d7076280f15c4cc89/Lib/fontbakery/profiles/googlefonts_conditions.py#L50

Does that error make sense to you? Is it correct? Am I running FontBakery properly?
Is there a way to address both that error and this issue?

**Comment by davelab6** [comment]
I believe this is a bug in Font Bakery; the weight axis should have named instances for Thin and ExtraLight at 100 and 200. 

The "no OS/2 usWeightClass value below 250" dogma was to prevent OpenType CFF (`.otf`) fonts from being auto-bolded by the Windows OS, and it sort of made sense to have the CFF and TTF flavors as similar as possible, but in 2019 when TTF flavor VFs are currently more widely supported than CFF2 flavor VFs, that FB check doesn't make sense. 

@felipesanches

**Comment by thisisdano** [comment]
Addressed in https://github.com/uswds/public-sans/pull/123
