### ISSUE TITLE
Light font weight not working in Figma

### ISSUE THREAD

**Issue by maya** [uswds/public-sans#120]
<img width="425" alt="Screen Shot 2019-10-23 at 12 45 11 PM" src="https://user-images.githubusercontent.com/5249443/67428557-37ff8100-f593-11e9-9f08-2931d219aadd.png">

**Comment by thisisdano** [comment]
I'm not sure what file format you're adding to Figma (TTF?), but can you try adding the files from https://github.com/uswds/public-sans/tree/develop/binaries and see if it helps?

Light TTF: https://github.com/uswds/public-sans/raw/develop/binaries/webfonts/PublicSans-Light.ttf

Light OTF: https://github.com/uswds/public-sans/raw/develop/binaries/otf/PublicSans-Italic.otf

**Comment by thisisdano** [comment]
Addressed in https://github.com/uswds/public-sans/pull/123
