### ISSUE TITLE
Different glyph list between Romans & Italics

### ISSUE THREAD

**Issue by cssobral2013** [uswds/public-sans#13]
If you need, see the folder in Drive:
https://drive.google.com/folderview?id=1fTeM4huxPa9qkzq5k4XZWBCU93qnSNY5

**Comment by thisisdano** [comment]
After a long delay, I'm finally getting back to this. Thanks for submitting this issue

**Comment by davelab6** [comment]
@thisisdano anything anyone can do to help with this? :)

**Comment by cssobral2013** [comment]
@davelab6 and @thisisdano: For this change to happen, we're needing to implement Vietnamese support, single-storey 'g' (see #38) and plain 'l' on romans, and some glyphs (such as 'IJ') on italics. The first part is easy: just redo the italics by obliqueing the romans by 8 degrees and correcting the glyphs. But, what do we do with the italics-only features?

**Comment by thisisdano** [comment]
OK :) Now's the time.

**Comment by thisisdano** [comment]
@cssobral2013 I don't see anything related to glyph list differences in that folder you shared. If you have a list/diff can you point me to it again?

**Comment by thisisdano** [comment]
nm. got it.

**Comment by thisisdano** [comment]
OK, here's my list of differences. I can work with this.

## only in italic
- `Abreveacute`
- `Abrevedotbelow`
- `Abrevegrave`
- `Abrevehookabove`
- `Abrevetilde`
- `Acircumflexacute`
- `Acircumflexdotbelow`
- `Acircumflexgrave`
- `Acircumflexhookabove`
- `Acircumflextilde`
- `Adotbelow`
- `Ahookabove`
- `Ecircumflexacute`
- `Ecircumflexdotbelow`
- `Ecircumflexgrave`
- `Ecircumflexhookabove`
- `Ecircumflextilde`
- `Ehookabove`
- `Ihookabove`
- `Ocircumflexacute`
- `Ocircumflexdotbelow`
- `Ocircumflexgrave`
- `Ocircumflexhookabove`
- `Ocircumflextilde`
- `Ohookabove`
- `Ohorn`
- `Ohornacute`
- `Ohorndotbelow`
- `Ohorngrave`
- `Ohornhookabove`
- `Ohorntilde`
- `Uhookabove`
- `Uhorn`
- `Uhornacute`
- `Uhorndotbelow`
- `Uhorngrave`
- `Uhornhookabove`
- `Uhorntilde`
- `Ydotbelow`
- `Yhookabove`
- `abreveacute`
- `abrevedotbelow`
- `abrevegrave`
- `abrevehookabove`
- `abrevetilde`
- `acircumflexacute`
- `acircumflexdotbelow`
- `acircumflexgrave`
- `acircumflexhookabove`
- `acircumflextilde`
- `adotbelow`
- `ahookabove`
- `ecircumflexacute`
- `ecircumflexdotbelow`
- `ecircumflexgrave`
- `ecircumflexhookabove`
- `ecircumflextilde`
- `ehookabove`
- `ihookabove`
- `ocircumflexacute`
- `ocircumflexdotbelow`
- `ocircumflexgrave`
- `ocircumflexhookabove`
- `ocircumflextilde`
- `ohookabove`
- `ohorn`
- `ohornacute`
- `ohorndotbelow`
- `ohorngrave`
- `ohornhookabove`
- `ohorntilde`
- `uhookabove`
- `uhorn`
- `uhornacute`
- `uhorndotbelow`
- `uhorngrave`
- `uhornhookabove`
- `uhorntilde`
- `ydotbelow`
- `yhookabove`
- `g.001`
- `Ohm`
- `increment`
- `micro`
- `hookabovecomb`
- `horncomb`
- `brevecomb_acutecomb`
- `brevecomb_gravecomb`
- `brevecomb_hookabovecomb`
- `brevecomb_tildecomb`
- `circumflexcomb_acutecomb`
- `circumflexcomb_gravecomb`
- `circumflexcomb_hookabovecomb`
- `circumflexcomb_tildecomb`

## only in roman
- `DZ`
- `DZcaron`
- `Dz`
- `Dzcaron`
- `Gacute`
- `IJ`
- `LJ`
- `Lj`
- `NJ`
- `Nj`
- `dz`
- `dzcaron`
- `gacute`
- `ij`
- `lj`
- `napostrophe`
- `nj`
- `p.001`
- `q.001`
- `f_f.liga`
- `Delta`
- `Omega`
- `mu`
- `zero.osf`
- `period.tf`
- `comma.tf`
- `bullet.uc`
- `bulletoperator`

**Comment by thisisdano** [comment]
Fixed in https://github.com/uswds/public-sans/pull/64
