### ISSUE TITLE
Investigate dashes jumping back rather than making a space

### ISSUE THREAD

**Issue by afeijoo** [uswds/public-sans#146]
When I was going to make templates, I came across a problem that I wonder about. When I make a "-" or a ”–" the dash jump back rather than make a space. Is this a bug or what?

Submitted via [ticket #17643](https://searchusa.zendesk.com/agent/tickets/17643)

**Comment by thisisdano** [comment]
This is most likely related to something about the face that we intend to be a feature: that we use a contextual alternate for the em-dash character when it is surrounded by spaces. This contextual alternate has less space in its sidebearings and is intended to make the space surrounding an em-dash more even, whether or not you manually add spaces before and after. 

![emdash-calt-spacing](https://user-images.githubusercontent.com/11464021/76006955-2378b100-5ec2-11ea-9fd4-0d4d11caf9ae.png)

This should only apply to the em-dash character, and not to any other dash (hyphen, en-dash, etc). You can see the rule in the font's code here: https://github.com/uswds/public-sans/blob/3c39c6422b9bdb5caccf0362f67dd8f28805770c/src/ufo/PublicSans-Black.ufo/features.fea#L280

If this functionality becomes bothersome, users can disable contextual alternates in your layout software.
