### ISSUE TITLE
Listing/naming of weights in MS office

### ISSUE THREAD

**Issue by KittyOh** [uswds/public-sans#193]
UPDATE
I've got these to work now in PowerPoint by using v.1.08 and by only installing the ttf files from the Web fonts folder (the OTFs won't install on my Mac or any of my colleagues). Please can I add a request? It wasn't clear to me which version was in the fonts folder in this repository – please can you add the version number to the folder name?
_____

Hi
My first post here, so hope I've done this correctly!

I'm trying to use Public Sans in MS Office on a Mac. It doesn't seem to be displaying the weight names correctly. See this screengrab:
![Screenshot 2021-04-06 at 17 17 14](https://user-images.githubusercontent.com/41117726/113744961-164d7780-96fd-11eb-9288-df6e2b1eb03f.png)
The different weights do work, but obviously it's trial and error trying to figure out which is the right weight!

I'm using version 1.007 downloaded from Google Fonts. I'm using the static TTF version.

I also removed the TTF version and tried the Variable version, which yielded this result:
![Screenshot 2021-04-06 at 17 43 14](https://user-images.githubusercontent.com/41117726/113748085-f9667380-96ff-11eb-8e75-81bada9102e5.png)

I also downloaded the OTF version from here, but my Mac wouldn't install it, citing critical errors as the reason.

MS Word is v16.37 and is up to date (as of just now).

The typeface works perfectly in Adobe CC Indesign.

Can you help? Sorry if this is user error!

**Comment by mejiaj** [comment]
Thanks for reporting this, I'll add it to our project board so we can triage.

**Comment by KittyOh** [comment]
Just to say, v 1.08 works fine now (but only the TTF files from the web fonts folder). 
And Google is still serving v1.07, as I'm sure you're aware.

**Comment by thlinard** [comment]
More generally, there is several issues in the `STAT` table:

- No Italic axis and Italic instances (you need two instances: Roman, elided, in the Roman font, and Italic in the Italic font, linked in Format 3).
- Italic used to define instances of the Weight axis (you could only do that for fvar instances, but the very principle of STAT is to separate axes).
- Regular instance should use format 3 to be linked to Bold.

See https://github.com/google/fonts/issues/2391

`gftools gen-stat` could solve these issues.
