### ISSUE TITLE
Sync italics based on romans

### ISSUE THREAD

**Issue by cssobral2013** [uswds/public-sans#21]
This font's italics look different from romans.

**Comment by fredrikhemsen** [comment]
I’m pretty sure the upright style is supposed to look different than the italic.

**Comment by cssobral2013** [comment]
So I'm proposing italics synced with romans for this font. See the file I attached.
[Public-Sans-new-Italics.zip](https://github.com/uswds/public-sans/files/3064446/Public-Sans-new-Italics.zip)

**Comment by maya** [comment]
@thisisdano was this resolved in #67?

**Comment by thisisdano** [comment]
New italic available for preview here: https://federalist-proxy.app.cloud.gov/preview/uswds/public-sans/dw-new-italic/

**Comment by thisisdano** [comment]
#67 was just a kerning sync — this new PR goes a lot further.
https://github.com/uswds/public-sans/pull/73

**Comment by cssobral2013** [comment]
This issue will be closed due to the #73 pull request.
