### ISSUE TITLE
Update URL

### ISSUE THREAD

**Issue by maya** [uswds/public-sans#23]
Can we change the URL from `18franklin.18f.gov` to `public-sans.digital.gov`? 

/cc @thisisdano @jeremyzilar

**Comment by thisisdano** [comment]
hm, that would be an improvement

**Comment by jeremyzilar** [comment]
I’m happy to help here. Feel free to assign to me.

**Comment by jeremyzilar** [comment]
@maya @thisisdano — I will set this up tomorrow and have it ready to push on Mon.

**Comment by thisisdano** [comment]
What's the current status of this issue?

**Comment by maya** [comment]
The status of this is that the Federalist team (@amirbey) has submitted the site to GSA IT for security scanning.

**Comment by maya** [comment]
This is done: https://public-sans.digital.gov/

Thanks @jeremyzilar 🎉
