### ISSUE TITLE
Wrong weight on alternative `g` glyph

### ISSUE THREAD

**Issue by linzhiq** [uswds/public-sans#242]
The alternative `g.ss01` glyph is always rendered with weight 100 in all weights of the variable roman version. `g.ss01` can be triggered on the ASCII `g` with OpenType features `salt` or `ss01` turned on. 

Tested on release v2.0 from this repo and Google Fonts with Figma and another design tool.

![SALT](https://user-images.githubusercontent.com/21976938/159994902-05e1805b-d79b-46ac-aa5b-3638471be65d.png)

Figma file: https://www.figma.com/file/U9oa7FiqqG1W48pDWXKxEr/'salt'-on-Public-Sans?node-id=0%3A1

**Comment by kenmcd** [comment]
Google Fonts web fonts do not support `salt` or `ss01` 
So what I expect would happen is nothing (original g).
But what appears to be happening is the alternate g from the default master (Thin).
Which is a bit unexpected (???).
I tested the desktop variable fonts for both v2.000 and v2.001 and they appear to be fine. 
`salt` demo is below:

![2022-03-24_13-05-40](https://user-images.githubusercontent.com/844920/160001259-5757cd51-d568-418a-8cd6-04a02edec741.gif)

**Comment by linzhiq** [comment]
Ah whoops. Seems like this is a bug with the Google Fonts distribution (which does have `salt` and `ss01`) which is still running v 1.006. 

Going to close this out in favor of https://github.com/google/fonts/issues/3953.

**Comment by kenmcd** [comment]
> Seems like this is a bug with the Google Fonts distribution (which does have `salt` and `ss01`)

Well that is interesting. It is my understanding that only the fonttools sub-setting defaults are available (which do not include those).
If you host the current fonts from the repo yourself it should work.
