### ISSUE TITLE
Release is missiong the OFL.txt

### ISSUE THREAD

**Issue by RosaWagner** [uswds/public-sans#250]
License should be in [public-sans-v2.001.zip](https://github.com/uswds/public-sans/releases/download/v2.001/public-sans-v2.001.zip)

**Comment by thisisdano** [comment]
Updated: https://github.com/uswds/public-sans/releases/download/v2.001/public-sans-v2.001.zip

### Updated ZIP (5.16.22)
Updated the ZIP file to include all the license and contributing information in addition to `sources/` and `fonts/` which were in the initial ZIP. The font files are unchanged from the initial ZIP.

#### ZIP contents: 
- `sources/`
- `fonts/`
- `OFL.txt`
- `FONTLOG.txt`
- `README.md`
- `AUTHORS.txt`
- `CONTRIBUTING.md`
- `CONTRIBUTORS.txt`
- `DESCRIPTION.en_us.html`
- `LICENSE.md`
