### ISSUE TITLE
Public Sans - Bug: Update uswds compile to ^1.0.0-beta.3

### ISSUE THREAD

**Issue by amyleadem** [uswds/public-sans#257]
### Describe the bug

Dependabot has flagged an `nth-check` security vulnerability tied to @uswds/compile@1.0.0-beta.2

### Steps to reproduce the bug

View this [Dependabot alert](https://github.com/uswds/public-sans/security/dependabot/13) to view details on the vulnerability.

### Expected Behavior

Updating to @uswds/compile@1.0.0-beta.3 will update this transitive dependency to 2.0.1 and remove the vulnerability. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/public-sans/issues) for duplicate bug reports.

**Comment by mejiaj** [comment]
Closing as outdated, we're on a much newer version of compile
https://github.com/uswds/public-sans/blob/7bff593bb5e0267e830e3411490dadb3d9a32d46/package.json#L39
