### ISSUE TITLE
License does not follow best practices and usage intention

### ISSUE THREAD

**Issue by thisisdano** [uswds/public-sans#28]
We want to Public Sans to be a good open-source project and follow SIL OFL guidance, requirements, and best practices. 

- [x] We've incorrectly removed the original copyright from Impallari Type's Libre Franklin. This was a mistake and the original copyright should be reinstated. See https://github.com/impallari/Libre-Franklin/blob/master/OFL.txt#L57-L58
- [x] We improperly claim a reserved font name (RFN) because this would require anyone using the font who subsets or otherwise makes any modification whatsoever to rename it. We have no business interest in an RFN and we do not wish to make that re-use restriction on Public Sans — we should remove it from https://github.com/uswds/public-sans/blob/master/ofl.txt#L2
- [x] We'll also need to look at the LICENSE.md in `uswds` to make sure it's in sync with the copyright information we have here. (https://github.com/uswds/uswds/blob/release-2.0/LICENSE.md)

cc @impallari @davelab6

**Comment by thisisdano** [comment]
This repo's license issues fixed in https://github.com/uswds/public-sans/pull/27

**Comment by thisisdano** [comment]
`uswds` repo PR: https://github.com/uswds/uswds/pull/2986

**Comment by maya** [comment]
Can this be closed?

**Comment by thisisdano** [comment]
Yes, fixed in uswds/uswds#2986 and #27
