### ISSUE TITLE
the OFL-1.1. license violates the Establishment Clause

### ISSUE THREAD

**Issue by mbutterick** [uswds/public-sans#31]
Amendment I of the Constitution of the United States prohibits US gov’t acts that “respect[] an establishment of religion”. OFL-1.1 is shorthand for the full name, which is “SIL Open Font License Version 1.1”. According to its website, SIL is a “[faith-based](https://www.sil.org/about)” organization. Linguists Lise Dobrin & Jeff Good [describe SIL](http://muse.jhu.edu/article/363179) more specifically as a “Christian missionary organization” whose main work is “Bible translation”. The US gov’t should not be using this license, as it creates an explicit entanglement / endorsement of a religious organization.

**Comment by sixty4k** [comment]
IANAL, but I doubt that using a common public license asserts a relationship with the original authors of the license.

**Comment by evbarnett** [comment]
I am also not a lawyer, but I know this is not how the Establishment Clause works. By your logic, Catholic universities couldn't be accredited, religious non-profits couldn't be legal charities, etc., which is obviously not the case.

Using a license that was originally created by a 'faith-based organization' is *not* an endorsement of the author, organization, religion, or anything in particular.

**Comment by mbutterick** [comment]
The analogy to “Catholic universities” and “religious … legal charities” is inapt. At issue here is a US gov’t work. This work can only be used if one assents to a certain license. The license was created by a religious organization (SIL) and remains explicitly associated with that organization (their name and hyperlink appears in the license). The license is [not incidental](https://www.sil.org/about/news/sil-international-releases-two-fonts-charis-sil-and-doulos-sil) to SIL’s religious purpose.

As for a possibly more apt analogy, a long line of cases (e.g., _[Warner vs. Orange County](https://caselaw.findlaw.com/us-2nd-circuit/1433805.html)_ and _[Inouye vs. Kemna](https://caselaw.findlaw.com/us-9th-circuit/1008140.html)_) has held that gov’t-mandated participation in Alcoholics Anonymous violates the Establishment Clause, even though AA is not formally associated with a particular church or religion.

For reasons cited in #30, `public-sans` should be put into the public domain, which would cure this issue as well (because it would no longer be subject to any license)

**Comment by evbarnett** [comment]
Your comparison to AA is not relevant. AA was not allowed because AA's plan itself contains religious goals. If AA's plan did not contain this content, AA could have even been associated with a specific church and it would have been fine. In short, content and intent is what matters, not basic affiliation.

Regarding #30, I commented there too. I do not believe this is public domain, since the project is based on Libre Franklin. Libre Franklin holds the original rights, and Public Sans must adhere to their license. It would be a violation for the US government to declare that Libre Franklin's work, which was not done by a government employee, is in the public domain.

**Comment by david-a-wheeler** [comment]
No. Using something produced by a religious organization, and then allowing anyone else to use the improvements made by the government, does not violate the establishment clause.  The US government works with faith-based organizations all the time (and rightly so).

**Comment by davelab6** [comment]
> Libre Franklin holds the original rights

Rather, the authors who have copyrights in the Libre Franklin project hold original rights.

**Comment by EssbieWGT** [comment]
@mbutterick just curious: 

- What cause of action is present and by whom if you're right about this OFL-1.1 issue? 
- What rights would the government have under OFL-1.1 that they do not possess if public-sans is in the public domain? 
- How can this issue have any effect on the copyrights related fonts it's arguably derived from when the stated legislative intent of Section 105 is that "publication or other use by the Government of a private work would not affect its copyright protection in any way." (See, e.g., H. Rept. 94-1476 at 60)

**Comment by thisisdano** [comment]
Addressed in #123
