### ISSUE TITLE
alternate lowercase g

### ISSUE THREAD

**Issue by errantspark** [uswds/public-sans#34]
I would be very interested in seeing an option for a single-story or monocular g in this typeface. Overall I'm very pleased with this and I wish I could contribute directly, unfortunately I don't have access to Glyphs or a MacOS computer.

My feeling is that the binocular g currently included stands out quite a bit from the rest of the characters. It's very old-timey and busy compared with the rest of the typeface, I don't think it fits the modern look that's embodied by the rest of the glyphs.

I think it would be a better default, but barring that an option for a monocular g would make this font more stylistically consistent, especially in more modern designs.

**Comment by thisisdano** [comment]
Added an in-progress version of a single-story `g` as a stylistic alternative (`ss01`) in https://github.com/uswds/public-sans/pull/64

It's not quite there yet and will continue to get some love in subsequent PRs.

I will say, however, that I like the 2-story `g` in most cases, as it ties back into the original franklin style and provides a bridge between the modern style and the older one.

<img width="648" alt="Screen Shot 2019-04-13 at 1 17 23 PM" src="https://user-images.githubusercontent.com/11464021/56084851-84048880-5dee-11e9-8dce-6370f1f252ed.png">
<img width="676" alt="Screen Shot 2019-04-13 at 1 17 09 PM" src="https://user-images.githubusercontent.com/11464021/56084853-8666e280-5dee-11e9-903d-d92394ae54c1.png">
<img width="680" alt="Screen Shot 2019-04-13 at 1 17 37 PM" src="https://user-images.githubusercontent.com/11464021/56084854-8961d300-5dee-11e9-8014-af2bcfa8c8b7.png">

**Comment by errantspark** [comment]
> as it ties back into the original franklin style and provides a bridge between the modern style and the older one

No arguments there, thank you for taking the time to do this! 

I've given it some more thought and I think I agree that the 2-story 'g' does have a bit more personality. I'm still glad to have the option for this one.

**Comment by danny-laa** [comment]
@thisisdano Any news?
