### ISSUE TITLE
Missing Hawaiian Character: ʻ

### ISSUE THREAD

**Issue by ian4uh** [uswds/public-sans#35]
The font has support for most of the Hawaiian Diacritics (ĀāĪīŪūĒēŌō) but is missing the [ʻokina](https://en.wikipedia.org/wiki/%CA%BBOkina).

````Ā ā Ī ī Ū ū Ē ē Ō ō ʻ````

"the ʻokina is encoded as U+02BB ʻ MODIFIER LETTER TURNED COMMA, which can be rendered in HTML by the entity &#699; (or in hexadecimal form &#x02BB;)"

Should look similar to a left single quote but able to be told apart from the punctuation. Much like [this example from Wikipedia](https://en.wikipedia.org/wiki/%CA%BBOkina#/media/File:Okina-using-Linux-Libertine.svg). 

There are currently less than 30 fonts that support all the Hawaiian Characters on Google fonts, This font being available would greatly help Government sites.

**Comment by thisisdano** [comment]
I will absolutely add this. Mahalo!

**Comment by thisisdano** [comment]
Working on this here: https://github.com/uswds/public-sans/pull/51
I'll have some questions for you as I go — and I'd appreciate it if you could test it before we merge it in.

**Comment by moyogo** [comment]
I don’t think making it smaller than the single quotation mark is a good idea. At smaller sizes or at a distance it just becomes a dot-like blob.

**Comment by moyogo** [comment]
In many fonts it looks exactly like the single quotation mark, which Libertine Linux correctly aims to avoid but with the wrong idea.

Would a semi-circle slightly with a rectangle, instead of a thinning diagonal with a square, larger than the single quotation mark be better?
![okina](https://user-images.githubusercontent.com/1923747/55819610-17894100-5af1-11e9-82e6-43e0d4e967f7.png)

**Comment by moyogo** [comment]
BTW U+02BC ʼ should use the same design as U+02BB ʻ but rotated. It currently looks like a condensed single quotation mark.

**Comment by thisisdano** [comment]
@moyogo I thought I would dislike the stylistic difference between an angled quote and a rounded 'okina, but I actually kinda like this. It gets the distinction across and has some resonance with the other letterforms (like the tail of the `l`). Thoughts?

<img width="825" alt="Screen Shot 2019-04-09 at 11 50 39 AM" src="https://user-images.githubusercontent.com/11464021/55826884-cf046000-5abd-11e9-8edc-4e5c523ea6ae.png">
<img width="809" alt="Screen Shot 2019-04-09 at 11 51 02 AM" src="https://user-images.githubusercontent.com/11464021/55826907-d88dc800-5abd-11e9-8c28-08d9ad5fb608.png">
<img width="860" alt="Screen Shot 2019-04-09 at 11 51 42 AM" src="https://user-images.githubusercontent.com/11464021/55826916-daf02200-5abd-11e9-9e63-6762761d9c91.png">

**Comment by moyogo** [comment]
It’s much better. I think the vertical shift compared with the single quotation mark helps.

**Comment by thisisdano** [comment]
Gonna tweak a bit, merge in and we can go from there. Definitely better than where it was (which was nothing!).

**Comment by ian4uh** [comment]
Yeah, the vertical shift helps a lot. I think most fonts do an upward shift, but Iʻm partial to the Libertine-ish downward shift. 

As long as the ʻokina has a distinct 6 shape it should be fine. The curved tops helps with that as well. I would not recommend using the rectangle approach mentioned earlier.

I made a pen that lists all the [Hawaiian supported Google Fonts](https://codepen.io/IMitchener/pen/aPqwry) I could find as an example.
