### ISSUE TITLE
Number Font issue in Notepad++

### ISSUE THREAD

**Issue by butu5** [uswds/public-sans#36]
![image](https://user-images.githubusercontent.com/354596/55765753-86947480-5ab4-11e9-8a69-9bb58f5cb1e0.png)
![image](https://user-images.githubusercontent.com/354596/55765784-a62b9d00-5ab4-11e9-8018-44d429d2287d.png)
I am using default "Public Sans" font size 10 in Notepad++.

**Comment by thisisdano** [comment]
The numbers aren't monospaced by default, though they do have a monospaced variant if. I'm not certain how you activate that opentype feature in Notepad++ though. That said, the left sidebearing of the `1` looks too tight in general and I should fix that.

**Comment by thisisdano** [comment]
We've fixed the number spacing in subsequent versions, though the default is still not monospaced
