### ISSUE TITLE
“Text or display” makes no sense

### ISSUE THREAD

**Issue by lofye** [uswds/public-sans#37]
I think you mean for “print or display”.
Because displays still display text.

**Comment by davelab6** [comment]
This is correct - its typography talk, meaning text for small point size
use, and display for large pt size.

**Comment by frankrolf** [comment]
Maybe amending with “sizes” would make it clearer?

**Comment by thisisdano** [comment]
I'll go ahead and amend with @frankrolf's suggestion

**Comment by thisisdano** [comment]
Does this seem like an improvement?
https://federalist-proxy.app.cloud.gov/preview/uswds/public-sans/dw-update-home-text/
