### ISSUE TITLE
Release version is outdated

### ISSUE THREAD

**Issue by snowl** [uswds/public-sans#38]
I tried to start using Public Sans on my website but hit some rendering issues (mainly #24). I then tried the version that is within the git repository and that seemed to render correctly. The released version is from 6 Oct 2018 - is there any plans to release an updated version?

Thanks

**Comment by thisisdano** [comment]
Yup — the released version is old now. I will update with a new GH release within the next week. Probably next Monday. (Though I am glad the render improved in the newer files. Was it something like https://github.com/uswds/public-sans/issues/24?)

**Comment by fredrikhemsen** [comment]
I would personally structure the repository to keep binary, exported font files, strictly separate from the source. If you update the release with each commit, you get a much cleaner workflow.

**Comment by snowl** [comment]
Yeah, #24 was the main issue I was hitting. Thanks!
