### ISSUE TITLE
Conflation of kerning, tracking, spacing

### ISSUE THREAD

**Issue by frankrolf** [uswds/public-sans#40]
This image https://github.com/uswds/public-sans#tighter-kerning-as-the-face-gets-heavier is described with “tighter kerning as the face gets heavier”.

When talking about type, it’s very common to hear spacing and kerning mixed up, but given the nature of this repository, I think it’s important to get things right:

- **spacing**: the general decision of space distribution built into a typeface. For example: _“This 1970s design is very tightly spaced”_
- **kerning**: an exception to the default spacing, wherever necessary – for instance in the combination `A V`. Example: _“I hope you didn’t kern the tabular figures”_
- **tracking**: changing the letterfit of a longer run of text. Example: _“I usually track out small captions if there’s no dedicated caption font available”_

This image https://raw.githubusercontent.com/uswds/public-sans/master/examples/public-sans-featured-images/public-v-lf-looser-tracking.png is captioned with “looser tracking”.

I propose changing the caption of the first image to “tighter spacing” …
I propose changing the caption of the 2nd image to “looser spacing” …

NB: _tighter spacing as the face gets heavier_ is something completely normal in typeface design, so perhaps not worthy of additional emphasis.

**Comment by thisisdano** [comment]
Good distinction, and a bit of sloppiness on my part. I'll make sure it's fixed

**Comment by thisisdano** [comment]
Fixed in https://github.com/uswds/public-sans/pull/49

**Comment by fredrikhemsen** [comment]
> When talking about type, it’s very common to hear spacing and kerning mixed up, but given the nature of this repository, I think it’s important to get things right:
> 
> * **spacing**: the general decision of space distribution built into a typeface. For example: _“This 1970s design is very tightly spaced”_
> * **kerning**: an exception to the default spacing, wherever necessary – for instance in the combination `A V`. Example: _“I hope you didn’t kern the tabular figures”_
> * **tracking**: changing the letterfit of a longer run of text. Example: _“I usually track out small captions if there’s no dedicated caption font available”_
 “looser tracking”.
Rarely do I see such intuitive explanations of these terms, thank you.

> NB: _tighter spacing as the face gets heavier_ is something completely normal in typeface design, so perhaps not worthy of additional emphasis.
I find this to be rather humorous.
