### ISSUE TITLE
The dots on the i and j differ in size

### ISSUE THREAD

**Issue by jdhoek** [uswds/public-sans#43]
The dots on the i and j differ significantly. This looks like a change introduced not present in Libre Franklin. The difference is most pronounced in weights ≤ 700.

![Screenshot from 2019-04-09 10-50-27](https://user-images.githubusercontent.com/683699/55786835-4ed9fc80-5ab5-11e9-973c-b9950e36b3f5.png)

Is this a conscious design choice or a design flaw?

The difference is rather jarring in words like *hijacker*.

**Comment by adamschwartz** [comment]
See https://github.com/uswds/uswds/issues/3024

**Comment by thisisdano** [comment]
Fixed in https://github.com/uswds/public-sans/pull/48
