### ISSUE TITLE
File naming convention for Regular and Italic

### ISSUE THREAD

**Issue by dellow** [uswds/public-sans#44]
The file naming of the regular weight is bit confusing to me. All font weight are named by their weight then, if italicized, with "italic" e.g. `PublicSans-Black` and `PublicSans-BlackItalic`.

However, the "regular" weight does not follow this convention, it has a `PublicSans-Regular` with a corresponding `PublicSans-Italic`. I would expect this to be: `PublicSans-RegularItalic`

**Comment by fredrikhemsen** [comment]
It is typical for type designers to omitt parts of the style name, wherever it does not deviate from the default. Some could even argue that `PublicSans-Regular` should be shortened to simply `PublicSans` do to the fact that the regular weight is the default in a font family.
 I am, however, against this school of thought and do, as you suggest, write out the full stylenames, but by this logic you would end up with `PublicSans-RegularUpright` and `PublicSans-RegularItalic`. This way, each style receives the same amount of variables, which looks cleaner and is easier to sort in a filesystem like the one on GitHub. If you were to add widths and optical sizes to the mix, you would end up with monstrosities like `PublicSans-DisplayCondensedBoldItalic` and `PublicSans-TextMediumRegularUpright`, which I personally think look pretty cool. If I someday were to design a massive font family, I’ll definitely be writing each PostScript name out like that.

**Comment by davelab6** [comment]
For me this is rational, but it's illogical, because my prime logic is to do what human users expect, not what may be convenient for machines. And fonts have decades of convention to not be named `-RegularItalic` but just `-Italic` :)

**Comment by dellow** [comment]
@davelab6 I'm a human and not a machine, I'd expect `RegularItalic` BUT I take your point and given you work on Google Fonts I'll concede you probably know more about what other humans expect in font naming logic than I do!

**Comment by moyogo** [comment]
Imagine the font family is expanded with condensed widths.

By the current convention one should expect `PublicSans-Condensed` instead of `PublicSans-CondensedRegular`, and `PublicSans-Regular` would not be renamed as `PublicSans-NormalRegular`, nor `PublicSans-Italic` as `PublicSans-NormalItalic`.
Similary `PublicSans-Regular` is not called `PublicSans-RegularUpright`.

By convention, the default weight, width, slant (or any design axis) name is dropped when another indicator is present.

**Comment by maya** [comment]
Thanks for the suggestions, but it appears the font is aligned with current font naming conventions.
