### ISSUE TITLE
Numerals are not equally strong

### ISSUE THREAD

**Issue by ri0t** [uswds/public-sans#46]
1st of all: Nice font!
I found a few issues with the numerals, though:

To reproduce:
* Select 'Black 900' variant - this way, the issues stand out a bit more
* Squint at numerals (maybe increase distance to your screen, a bit)
=> Numeral '4' is clearly too strong
=> Numeral '0' might be a bit too strong
=> Tabular '1' is much stronger than '2' or '3'

There are other minor issues with the numerals, too, but they might be part of the design. 
E.g. maybe check the joint thickness of numeral '2'

**Comment by thisisdano** [comment]
Thanks. I'm going to take a look at this — I think there are some spacing issues I might be able to resolve at the same time.

**Comment by thisisdano** [comment]
Does this seem like an improvement?

<img width="762" alt="Screen Shot 2019-04-09 at 4 17 14 PM" src="https://user-images.githubusercontent.com/11464021/55841151-e9046980-5ae2-11e9-9d26-67b7ff96cdb6.png">
<img width="790" alt="Screen Shot 2019-04-09 at 4 16 59 PM" src="https://user-images.githubusercontent.com/11464021/55841155-edc91d80-5ae2-11e9-9803-7edbcabc3f63.png">
<img width="807" alt="Screen Shot 2019-04-09 at 4 16 50 PM" src="https://user-images.githubusercontent.com/11464021/55841163-f15ca480-5ae2-11e9-84b8-ca528b426985.png">
<img width="822" alt="Screen Shot 2019-04-09 at 4 16 41 PM" src="https://user-images.githubusercontent.com/11464021/55841166-f3befe80-5ae2-11e9-8890-78a960900a95.png">
