### ISSUE TITLE
Specimen pages don't list the correct weight in the "body" comparison blocks

### ISSUE THREAD

**Issue by webmaven** [uswds/public-sans#50]
The "body" font comparison blocks on the specimen pages (eg. https://public-sans.digital.gov/specimens/public-sans-thin.html) don't list the correct weight for Public Sans (it always says "Public Sans Black" regardless of the weight), and doesn't list the comparable weight of the other fonts at all (I guess the latter is more of a feature request):

![image](https://user-images.githubusercontent.com/438502/55817545-02d98880-5ab2-11e9-84e5-f110bad21c48.png)

**Comment by thisisdano** [comment]
Thanks! There's so much work to do on this janky little specimen page. But I would like to fix this.

**Comment by webmaven** [comment]
What are the other issues specific to the specimen pages?

A quick fix that would make the blocks consistent on all pages would be to just remove the word "Black".

**Comment by thisisdano** [comment]
Yeah — I can just make that fix. The big issues are that the site isn't mobile friendly and has accessibility issues. And that it's a PITA to update. Other than that, perfect!
