### ISSUE TITLE
Why did you chose proportional figures for this typeface?

### ISSUE THREAD

**Issue by cssobral2013** [uswds/public-sans#62]

**Comment by otherjoel** [comment]
Per the docs, the font includes tabular figures.

**Comment by cssobral2013** [comment]
Then, why did you chose proportional figures as the default ones?

**Comment by otherjoel** [comment]
1. I didn’t.
2. It’s a common choice for a proportional font.
3. There is no problem here.

**Comment by thisisdano** [comment]
To the best of my knowledge, this is the convention for figures: proportional as the default and monospaced/tabular as an alternate. This is consistent with the glyph naming, where a character like `zero` is the base glyph and `zero.tf` is the tabular alternate.

**Comment by cssobral2013** [comment]
Okay then. I'll close this issue.
