### ISSUE TITLE
Italics are still reminiscent of 18Franklin

### ISSUE THREAD

**Issue by cssobral2013** [uswds/public-sans#63]

**Comment by thisisdano** [comment]
True. The italics could still use some love and are much closer to their source than the romans. That said, I was comfortable releasing them as some of their features (more modulated stroke, angled terminals) could be appropriate for an italic. They're also just a simple skew, and making something a little more _italic_ could be a focus for future work.

**Comment by cssobral2013** [comment]
This issue was closed 'cause a new italic was built from #73 pull request.
