### ISSUE TITLE
U+2044 (Fraction) and U+20A1 (colón) are defective in all Italics

### ISSUE THREAD

**Issue by cssobral2013** [uswds/public-sans#82]

**Comment by thisisdano** [comment]
I see that that colón is a little awkward, but can you explain a little more what makes it unacceptable? (i.e. point to the expected output?)

Also, what makes the fraction slash defective? To my eyes, it looks somewhat ungraceful and poorly spaced (and should be cleaned up) but not necessarily defective or broken. Can you give an example?

**Comment by cssobral2013** [comment]
For the fraction, it should have consistent width. For the colón, Its slash
should fully cross the 'c', as it happens in all romans.

Em seg, 22 de abr de 2019 00:53, Dan O. Williams <notifications@github.com>
escreveu:

**Comment by cssobral2013** [comment]
I got an idea: why not use uppercase 'C' to make the colóns, then apply a double slash?

**Comment by cssobral2013** [comment]
I got another idea: why not reverting the colón, 'perthousand' and 'percent' to Public Sans, version 1.000?

**Comment by thisisdano** [comment]
Oh, I'm surprised there was change from 1.000 to the current version. I will check that out.

**Comment by thisisdano** [comment]
OK — I see the regression and will fix.

**Comment by cssobral2013** [comment]
I forgot to mention - include 'fraction' on the change list.

**Comment by cssobral2013** [comment]
Another thing to note: Thin Italic and Black Italic DOESN'T display this problem, so it looks like an interpolation problem.
