### ISSUE TITLE
all central european diacritics wrong

### ISSUE THREAD

**Issue by tkapler** [uswds/public-sans#89]
all central european diactricis is wrong: ýáíé.. - acutes must start near the center and are almost vertical, not horizontal (the most problematic here is "í", where your acute looks like horizontal line above. 
all diactrics are inseparable component of the character (those are completely different characters with different pronunciation etc.) so they should be tighly connected, not so far above them.
Also kerning for "ď" is very wrong, if you write e.g. "ďábel" (devil in Czech) the kerning for ď is now about two times bigger than for the other letters.

**Comment by thisisdano** [comment]
Thanks @tkapler — I'll work on building some of those diacritics. (I've got a batch of diacritic work in the queue.) And I know what you've seen with the `ď` — I think I've fixed this in later builds, but I will double-check and make sure it's rendering as expected now. I'll post revisions here when I have them — would you be able to review them?

**Comment by tkapler** [comment]
Thanks, i will be delighted to review it, thank you

See Czech and Slovak pangrams:
Příliš žluťoučký kůň úpěl ďábelské ódy (Czech)
Kŕdeľ šťastných ďatľov učí pri ústí Váhu mĺkveho koňa obhrýzať kôru a žrať čerstvé mäso (Slovak)
First is public sans, second open sans. 
Tested just now with this TTF https://github.com/uswds/public-sans/blob/master/fonts/webfonts/PublicSans-Regular.ttf

![image](https://user-images.githubusercontent.com/1409898/56606258-19c9c000-6606-11e9-8a71-2de1c77992e9.png)

**Comment by thisisdano** [comment]
@tkapler Thanks for including the pangrams. Please check my test file here: https://federalist-proxy.app.cloud.gov/preview/uswds/public-sans/dw-diacritics/test/

<img width="800" alt="Screen Shot 2019-04-23 at 1 49 36 PM" src="https://user-images.githubusercontent.com/11464021/56614755-a193d800-65ce-11e9-8ecd-44647547bf90.png">


Does this change seem like an improvement?

**Comment by thisisdano** [comment]
A useful list of pangrams: http://clagnut.com/blog/2380/

**Comment by tkapler** [comment]
YES, this is almost perfect (i still think that the ď kerning should be smaller for the bolder versions, but i see it might be complicated for some higher letters combinations). Thank you

**Comment by thisisdano** [comment]
Thanks again. I think I improved the spacing in the `caron`-related glyphs across the board:

<img width="804" alt="Screen Shot 2019-04-24 at 10 21 17 AM" src="https://user-images.githubusercontent.com/11464021/56679786-bfb71200-667a-11e9-96b6-5a6fedc5aaf2.png">

**Comment by tkapler** [comment]
I love it, you are a hero.
