### ISSUE TITLE
Bold Font not Linked in MS Word

### ISSUE THREAD

**Issue by ToddOhl** [uswds/public-sans#90]
When using Public Sans in MS Word, assigning a **Bold** [Ctrl+B] weight seems to do nothing.

**Comment by ToddOhl** [comment]
This seems to happen only with the fonts in the master file -- the font packages downloaded from uswds for designers seems to be fine.

**Comment by thisisdano** [comment]
Can you check the fonts in https://github.com/uswds/public-sans/tree/master/fonts/otf and see if they resolve the issue? (I think I fixed it, but I'm not yet sure.)

**Comment by ToddOhl** [comment]
This looks like it fixed things. Sorry for the delayed reply.

**Comment by ToddOhl** [comment]
Thanks!
