### ISSUE TITLE
Bad rendering of all top rounded characters on Window in some particular sizes

### ISSUE THREAD

**Issue by fat32** [uswds/public-sans#96]
Screenshot of the issue: https://i.imgur.com/u5PfEjs.png
Screenshot was taken today on https://v2.designsystem.digital.gov/components/accordion/
Examples:
Public Sans (normal) 20px
Public Sans (bold) 9px, 11px, 13px, 15px, 17px, 19px.

**Comment by thisisdano** [comment]
OK, I can reproduce this, but now I have to learn how hinting works to attempt a fix.
